# Generated by Django 4.0.5 on 2022-06-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('work_state', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('source', models.CharField(max_length=200)),
            ],
        ),
    ]
