# Generated by Django 4.0.5 on 2022-06-22 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kywapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wage',
            name='timestamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
